#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 119
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 15

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_sig = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_abstract = 5,
  sym_var = 6,
  anon_sym_COMMA = 7,
  anon_sym_extends = 8,
  anon_sym_in = 9,
  anon_sym_PLUS = 10,
  anon_sym_disj = 11,
  anon_sym_COLON = 12,
  anon_sym_DASH = 13,
  aux_sym_constant_token1 = 14,
  aux_sym_constant_token2 = 15,
  anon_sym_none = 16,
  anon_sym_univ = 17,
  anon_sym_iden = 18,
  anon_sym_one = 19,
  anon_sym_lone = 20,
  anon_sym_some = 21,
  sym_source_file = 22,
  sym__definition = 23,
  sym_sig_definition = 24,
  sym_name_list = 25,
  sym__name_list = 26,
  sym_sig_extends = 27,
  sym_sig_in = 28,
  sym_sig_in_list = 29,
  sym_field_list = 30,
  sym__field_list = 31,
  sym_field_declaration = 32,
  sym_expression = 33,
  sym_constant = 34,
  sym_multiplicity = 35,
  sym_qualified_name = 36,
  sym_block = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_sig_in_list_repeat1 = 39,
  aux_sym_block_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_sig] = "sig",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_abstract] = "abstract",
  [sym_var] = "var",
  [anon_sym_COMMA] = ",",
  [anon_sym_extends] = "extends",
  [anon_sym_in] = "in",
  [anon_sym_PLUS] = "+",
  [anon_sym_disj] = "disj",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH] = "-",
  [aux_sym_constant_token1] = "constant_token1",
  [aux_sym_constant_token2] = "constant_token2",
  [anon_sym_none] = "none",
  [anon_sym_univ] = "univ",
  [anon_sym_iden] = "iden",
  [anon_sym_one] = "one",
  [anon_sym_lone] = "lone",
  [anon_sym_some] = "some",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_sig_definition] = "sig_definition",
  [sym_name_list] = "name_list",
  [sym__name_list] = "_name_list",
  [sym_sig_extends] = "sig_extends",
  [sym_sig_in] = "sig_in",
  [sym_sig_in_list] = "sig_in_list",
  [sym_field_list] = "field_list",
  [sym__field_list] = "_field_list",
  [sym_field_declaration] = "field_declaration",
  [sym_expression] = "expression",
  [sym_constant] = "constant",
  [sym_multiplicity] = "multiplicity",
  [sym_qualified_name] = "qualified_name",
  [sym_block] = "block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sig_in_list_repeat1] = "sig_in_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_sig] = anon_sym_sig,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_abstract] = sym_abstract,
  [sym_var] = sym_var,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_disj] = anon_sym_disj,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_constant_token1] = aux_sym_constant_token1,
  [aux_sym_constant_token2] = aux_sym_constant_token2,
  [anon_sym_none] = anon_sym_none,
  [anon_sym_univ] = anon_sym_univ,
  [anon_sym_iden] = anon_sym_iden,
  [anon_sym_one] = anon_sym_one,
  [anon_sym_lone] = anon_sym_lone,
  [anon_sym_some] = anon_sym_some,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_sig_definition] = sym_sig_definition,
  [sym_name_list] = sym_name_list,
  [sym__name_list] = sym__name_list,
  [sym_sig_extends] = sym_sig_extends,
  [sym_sig_in] = sym_sig_in,
  [sym_sig_in_list] = sym_sig_in_list,
  [sym_field_list] = sym_field_list,
  [sym__field_list] = sym__field_list,
  [sym_field_declaration] = sym_field_declaration,
  [sym_expression] = sym_expression,
  [sym_constant] = sym_constant,
  [sym_multiplicity] = sym_multiplicity,
  [sym_qualified_name] = sym_qualified_name,
  [sym_block] = sym_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sig_in_list_repeat1] = aux_sym_sig_in_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_sig] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_abstract] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_disj] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constant_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constant_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_univ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iden] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_one] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lone] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_some] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_sig_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym__name_list] = {
    .visible = false,
    .named = true,
  },
  [sym_sig_extends] = {
    .visible = true,
    .named = true,
  },
  [sym_sig_in] = {
    .visible = true,
    .named = true,
  },
  [sym_sig_in_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_list] = {
    .visible = true,
    .named = true,
  },
  [sym__field_list] = {
    .visible = false,
    .named = true,
  },
  [sym_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicity] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_name] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sig_in_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_extends = 1,
  field_fields = 2,
  field_in_list = 3,
  field_names = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_extends] = "extends",
  [field_fields] = "fields",
  [field_in_list] = "in_list",
  [field_names] = "names",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_names, 1},
  [1] =
    {field_extends, 1},
  [2] =
    {field_in_list, 1},
  [3] =
    {field_fields, 3},
    {field_names, 1},
  [5] =
    {field_names, 2},
  [6] =
    {field_fields, 4},
    {field_names, 1},
  [8] =
    {field_fields, 4},
    {field_names, 2},
  [10] =
    {field_names, 3},
  [11] =
    {field_fields, 5},
    {field_names, 2},
  [13] =
    {field_fields, 5},
    {field_names, 3},
  [15] =
    {field_names, 4},
  [16] =
    {field_fields, 6},
    {field_names, 3},
  [18] =
    {field_fields, 6},
    {field_names, 4},
  [20] =
    {field_fields, 7},
    {field_names, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 6,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 83,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 85,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '+') ADVANCE(5);
      if (lookahead == ',') ADVANCE(4);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '}') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_constant_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == 'v') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'x') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'j') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_one);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_sig);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'v') ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_var);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_disj);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_iden);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_lone);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_some);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_univ);
      END_STATE();
    case 42:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_abstract);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_sig] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_abstract] = ACTIONS(1),
    [sym_var] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_disj] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_constant_token1] = ACTIONS(1),
    [aux_sym_constant_token2] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [anon_sym_univ] = ACTIONS(1),
    [anon_sym_iden] = ACTIONS(1),
    [anon_sym_one] = ACTIONS(1),
    [anon_sym_lone] = ACTIONS(1),
    [anon_sym_some] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(118),
    [sym__definition] = STATE(2),
    [sym_sig_definition] = STATE(2),
    [sym_multiplicity] = STATE(115),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_sig] = ACTIONS(5),
    [sym_abstract] = ACTIONS(7),
    [sym_var] = ACTIONS(9),
    [anon_sym_one] = ACTIONS(11),
    [anon_sym_lone] = ACTIONS(11),
    [anon_sym_some] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      anon_sym_sig,
    ACTIONS(7), 1,
      sym_abstract,
    ACTIONS(9), 1,
      sym_var,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(115), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
    STATE(3), 3,
      sym__definition,
      sym_sig_definition,
      aux_sym_source_file_repeat1,
  [26] = 7,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_sig,
    ACTIONS(20), 1,
      sym_abstract,
    ACTIONS(23), 1,
      sym_var,
    STATE(115), 1,
      sym_multiplicity,
    ACTIONS(26), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
    STATE(3), 3,
      sym__definition,
      sym_sig_definition,
      aux_sym_source_file_repeat1,
  [52] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
    ACTIONS(29), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [68] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(96), 1,
      sym_field_list,
    STATE(105), 1,
      sym__field_list,
    STATE(107), 1,
      sym_name_list,
  [96] = 8,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    STATE(70), 1,
      sym__name_list,
    STATE(83), 1,
      sym__field_list,
    STATE(85), 1,
      sym_field_declaration,
    STATE(107), 1,
      sym_name_list,
    ACTIONS(41), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [122] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(101), 1,
      sym_field_list,
    STATE(105), 1,
      sym__field_list,
    STATE(107), 1,
      sym_name_list,
  [150] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_block,
    ACTIONS(45), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [166] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_block,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [182] = 5,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      anon_sym_DASH,
    STATE(58), 1,
      sym_constant,
    STATE(10), 2,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(54), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [202] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_block,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [218] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_block,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [234] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_block,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [250] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(98), 1,
      sym_field_list,
    STATE(105), 1,
      sym__field_list,
    STATE(107), 1,
      sym_name_list,
  [278] = 5,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(58), 1,
      sym_constant,
    STATE(10), 2,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [298] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_block,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [314] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(105), 1,
      sym__field_list,
    STATE(107), 1,
      sym_name_list,
    STATE(117), 1,
      sym_field_list,
  [342] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_block,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [358] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(105), 1,
      sym__field_list,
    STATE(106), 1,
      sym_field_list,
    STATE(107), 1,
      sym_name_list,
  [386] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_block,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [402] = 5,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_constant,
    STATE(15), 2,
      sym_expression,
      aux_sym_block_repeat1,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [422] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym_block,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [438] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_block,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [454] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_block,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [470] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_block,
    ACTIONS(89), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [486] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      sym_block,
    ACTIONS(91), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [502] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
    ACTIONS(93), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [518] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(104), 1,
      sym_field_list,
    STATE(105), 1,
      sym__field_list,
    STATE(107), 1,
      sym_name_list,
  [546] = 3,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
    ACTIONS(97), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [562] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(103), 1,
      sym_field_list,
    STATE(105), 1,
      sym__field_list,
    STATE(107), 1,
      sym_name_list,
  [590] = 9,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(92), 1,
      sym_field_declaration,
    STATE(105), 1,
      sym__field_list,
    STATE(107), 1,
      sym_name_list,
    STATE(109), 1,
      sym_field_list,
  [618] = 5,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      anon_sym_disj,
    STATE(58), 1,
      sym_constant,
    STATE(87), 1,
      sym_expression,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [637] = 8,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_disj,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym__name_list,
    STATE(84), 1,
      sym__field_list,
    STATE(85), 1,
      sym_field_declaration,
    STATE(107), 1,
      sym_name_list,
  [662] = 5,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(105), 1,
      anon_sym_disj,
    STATE(58), 1,
      sym_constant,
    STATE(81), 1,
      sym_expression,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [681] = 5,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(107), 1,
      anon_sym_disj,
    STATE(58), 1,
      sym_constant,
    STATE(94), 1,
      sym_expression,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [700] = 1,
    ACTIONS(109), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [710] = 1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [720] = 1,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [730] = 1,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [740] = 1,
    ACTIONS(113), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [750] = 1,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [760] = 1,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [770] = 1,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [780] = 1,
    ACTIONS(117), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [790] = 4,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(58), 1,
      sym_constant,
    STATE(81), 1,
      sym_expression,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [806] = 1,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [816] = 4,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(58), 1,
      sym_constant,
    STATE(91), 1,
      sym_expression,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [832] = 1,
    ACTIONS(121), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [842] = 4,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(58), 1,
      sym_constant,
    STATE(94), 1,
      sym_expression,
    ACTIONS(69), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [858] = 2,
    ACTIONS(125), 1,
      anon_sym_DASH,
    ACTIONS(123), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [870] = 1,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [880] = 1,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [890] = 1,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [900] = 1,
    ACTIONS(133), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [910] = 1,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [920] = 1,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [930] = 2,
    ACTIONS(141), 1,
      anon_sym_DASH,
    ACTIONS(139), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [942] = 2,
    ACTIONS(145), 1,
      anon_sym_DASH,
    ACTIONS(143), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [954] = 1,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [964] = 4,
    ACTIONS(149), 1,
      anon_sym_sig,
    ACTIONS(151), 1,
      sym_abstract,
    STATE(114), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [979] = 4,
    ACTIONS(153), 1,
      anon_sym_LBRACE,
    ACTIONS(155), 1,
      anon_sym_extends,
    ACTIONS(157), 1,
      anon_sym_in,
    STATE(99), 2,
      sym_sig_extends,
      sym_sig_in,
  [993] = 4,
    ACTIONS(155), 1,
      anon_sym_extends,
    ACTIONS(157), 1,
      anon_sym_in,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    STATE(116), 2,
      sym_sig_extends,
      sym_sig_in,
  [1007] = 4,
    ACTIONS(155), 1,
      anon_sym_extends,
    ACTIONS(157), 1,
      anon_sym_in,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    STATE(110), 2,
      sym_sig_extends,
      sym_sig_in,
  [1021] = 3,
    ACTIONS(163), 1,
      anon_sym_sig,
    STATE(108), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [1033] = 4,
    ACTIONS(155), 1,
      anon_sym_extends,
    ACTIONS(157), 1,
      anon_sym_in,
    ACTIONS(165), 1,
      anon_sym_LBRACE,
    STATE(111), 2,
      sym_sig_extends,
      sym_sig_in,
  [1047] = 2,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(167), 4,
      anon_sym_LBRACE,
      anon_sym_extends,
      anon_sym_in,
      anon_sym_COLON,
  [1057] = 3,
    ACTIONS(149), 1,
      anon_sym_sig,
    STATE(114), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [1069] = 4,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_disj,
    STATE(70), 1,
      sym__name_list,
    STATE(97), 1,
      sym_name_list,
  [1082] = 1,
    ACTIONS(173), 4,
      anon_sym_LBRACE,
      anon_sym_extends,
      anon_sym_in,
      anon_sym_COLON,
  [1089] = 1,
    ACTIONS(175), 4,
      anon_sym_LBRACE,
      anon_sym_extends,
      anon_sym_in,
      anon_sym_COLON,
  [1096] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(70), 1,
      sym__name_list,
    STATE(100), 1,
      sym_name_list,
  [1106] = 3,
    ACTIONS(179), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      anon_sym_PLUS,
    STATE(74), 1,
      aux_sym_sig_in_list_repeat1,
  [1116] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(65), 1,
      sym_name_list,
    STATE(70), 1,
      sym__name_list,
  [1126] = 3,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_PLUS,
    STATE(74), 1,
      aux_sym_sig_in_list_repeat1,
  [1136] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(62), 1,
      sym_name_list,
    STATE(70), 1,
      sym__name_list,
  [1146] = 3,
    ACTIONS(181), 1,
      anon_sym_PLUS,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      aux_sym_sig_in_list_repeat1,
  [1156] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(70), 1,
      sym__name_list,
    STATE(97), 1,
      sym_name_list,
  [1166] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(63), 1,
      sym_name_list,
    STATE(70), 1,
      sym__name_list,
  [1176] = 3,
    ACTIONS(190), 1,
      sym_identifier,
    STATE(76), 1,
      sym_qualified_name,
    STATE(95), 1,
      sym_sig_in_list,
  [1186] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(61), 1,
      sym_name_list,
    STATE(70), 1,
      sym__name_list,
  [1196] = 1,
    ACTIONS(192), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1201] = 2,
    ACTIONS(190), 1,
      sym_identifier,
    STATE(86), 1,
      sym_qualified_name,
  [1208] = 2,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    ACTIONS(196), 1,
      anon_sym_COMMA,
  [1215] = 2,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      anon_sym_COMMA,
  [1222] = 2,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    ACTIONS(203), 1,
      anon_sym_COMMA,
  [1229] = 1,
    ACTIONS(183), 2,
      anon_sym_LBRACE,
      anon_sym_PLUS,
  [1234] = 1,
    ACTIONS(206), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1239] = 1,
    ACTIONS(208), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1244] = 2,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(69), 1,
      sym__name_list,
  [1251] = 2,
    ACTIONS(190), 1,
      sym_identifier,
    STATE(102), 1,
      sym_qualified_name,
  [1258] = 1,
    ACTIONS(210), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1263] = 2,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 1,
      anon_sym_COMMA,
  [1270] = 1,
    ACTIONS(214), 2,
      anon_sym_LBRACE,
      anon_sym_PLUS,
  [1275] = 1,
    ACTIONS(216), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1280] = 1,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
  [1284] = 1,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
  [1288] = 1,
    ACTIONS(222), 1,
      anon_sym_COLON,
  [1292] = 1,
    ACTIONS(224), 1,
      anon_sym_RBRACE,
  [1296] = 1,
    ACTIONS(226), 1,
      anon_sym_LBRACE,
  [1300] = 1,
    ACTIONS(228), 1,
      anon_sym_COLON,
  [1304] = 1,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
  [1308] = 1,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
  [1312] = 1,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
  [1316] = 1,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
  [1320] = 1,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
  [1324] = 1,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
  [1328] = 1,
    ACTIONS(242), 1,
      anon_sym_COLON,
  [1332] = 1,
    ACTIONS(244), 1,
      anon_sym_sig,
  [1336] = 1,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
  [1340] = 1,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
  [1344] = 1,
    ACTIONS(250), 1,
      anon_sym_LBRACE,
  [1348] = 1,
    ACTIONS(252), 1,
      aux_sym_constant_token1,
  [1352] = 1,
    ACTIONS(254), 1,
      anon_sym_sig,
  [1356] = 1,
    ACTIONS(163), 1,
      anon_sym_sig,
  [1360] = 1,
    ACTIONS(149), 1,
      anon_sym_sig,
  [1364] = 1,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
  [1368] = 1,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
  [1372] = 1,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 68,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 122,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 166,
  [SMALL_STATE(10)] = 182,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 218,
  [SMALL_STATE(13)] = 234,
  [SMALL_STATE(14)] = 250,
  [SMALL_STATE(15)] = 278,
  [SMALL_STATE(16)] = 298,
  [SMALL_STATE(17)] = 314,
  [SMALL_STATE(18)] = 342,
  [SMALL_STATE(19)] = 358,
  [SMALL_STATE(20)] = 386,
  [SMALL_STATE(21)] = 402,
  [SMALL_STATE(22)] = 422,
  [SMALL_STATE(23)] = 438,
  [SMALL_STATE(24)] = 454,
  [SMALL_STATE(25)] = 470,
  [SMALL_STATE(26)] = 486,
  [SMALL_STATE(27)] = 502,
  [SMALL_STATE(28)] = 518,
  [SMALL_STATE(29)] = 546,
  [SMALL_STATE(30)] = 562,
  [SMALL_STATE(31)] = 590,
  [SMALL_STATE(32)] = 618,
  [SMALL_STATE(33)] = 637,
  [SMALL_STATE(34)] = 662,
  [SMALL_STATE(35)] = 681,
  [SMALL_STATE(36)] = 700,
  [SMALL_STATE(37)] = 710,
  [SMALL_STATE(38)] = 720,
  [SMALL_STATE(39)] = 730,
  [SMALL_STATE(40)] = 740,
  [SMALL_STATE(41)] = 750,
  [SMALL_STATE(42)] = 760,
  [SMALL_STATE(43)] = 770,
  [SMALL_STATE(44)] = 780,
  [SMALL_STATE(45)] = 790,
  [SMALL_STATE(46)] = 806,
  [SMALL_STATE(47)] = 816,
  [SMALL_STATE(48)] = 832,
  [SMALL_STATE(49)] = 842,
  [SMALL_STATE(50)] = 858,
  [SMALL_STATE(51)] = 870,
  [SMALL_STATE(52)] = 880,
  [SMALL_STATE(53)] = 890,
  [SMALL_STATE(54)] = 900,
  [SMALL_STATE(55)] = 910,
  [SMALL_STATE(56)] = 920,
  [SMALL_STATE(57)] = 930,
  [SMALL_STATE(58)] = 942,
  [SMALL_STATE(59)] = 954,
  [SMALL_STATE(60)] = 964,
  [SMALL_STATE(61)] = 979,
  [SMALL_STATE(62)] = 993,
  [SMALL_STATE(63)] = 1007,
  [SMALL_STATE(64)] = 1021,
  [SMALL_STATE(65)] = 1033,
  [SMALL_STATE(66)] = 1047,
  [SMALL_STATE(67)] = 1057,
  [SMALL_STATE(68)] = 1069,
  [SMALL_STATE(69)] = 1082,
  [SMALL_STATE(70)] = 1089,
  [SMALL_STATE(71)] = 1096,
  [SMALL_STATE(72)] = 1106,
  [SMALL_STATE(73)] = 1116,
  [SMALL_STATE(74)] = 1126,
  [SMALL_STATE(75)] = 1136,
  [SMALL_STATE(76)] = 1146,
  [SMALL_STATE(77)] = 1156,
  [SMALL_STATE(78)] = 1166,
  [SMALL_STATE(79)] = 1176,
  [SMALL_STATE(80)] = 1186,
  [SMALL_STATE(81)] = 1196,
  [SMALL_STATE(82)] = 1201,
  [SMALL_STATE(83)] = 1208,
  [SMALL_STATE(84)] = 1215,
  [SMALL_STATE(85)] = 1222,
  [SMALL_STATE(86)] = 1229,
  [SMALL_STATE(87)] = 1234,
  [SMALL_STATE(88)] = 1239,
  [SMALL_STATE(89)] = 1244,
  [SMALL_STATE(90)] = 1251,
  [SMALL_STATE(91)] = 1258,
  [SMALL_STATE(92)] = 1263,
  [SMALL_STATE(93)] = 1270,
  [SMALL_STATE(94)] = 1275,
  [SMALL_STATE(95)] = 1280,
  [SMALL_STATE(96)] = 1284,
  [SMALL_STATE(97)] = 1288,
  [SMALL_STATE(98)] = 1292,
  [SMALL_STATE(99)] = 1296,
  [SMALL_STATE(100)] = 1300,
  [SMALL_STATE(101)] = 1304,
  [SMALL_STATE(102)] = 1308,
  [SMALL_STATE(103)] = 1312,
  [SMALL_STATE(104)] = 1316,
  [SMALL_STATE(105)] = 1320,
  [SMALL_STATE(106)] = 1324,
  [SMALL_STATE(107)] = 1328,
  [SMALL_STATE(108)] = 1332,
  [SMALL_STATE(109)] = 1336,
  [SMALL_STATE(110)] = 1340,
  [SMALL_STATE(111)] = 1344,
  [SMALL_STATE(112)] = 1348,
  [SMALL_STATE(113)] = 1352,
  [SMALL_STATE(114)] = 1356,
  [SMALL_STATE(115)] = 1360,
  [SMALL_STATE(116)] = 1364,
  [SMALL_STATE(117)] = 1368,
  [SMALL_STATE(118)] = 1372,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(67),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(60),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(113),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 5, .production_id = 4),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 9, .production_id = 14),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 9),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(112),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(57),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 5, .production_id = 5),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 5, .production_id = 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 10),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 6),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 8),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 11),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 8),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 13),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 5),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 4, .production_id = 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 7),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 11),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 12),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 9, .production_id = 13),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 8),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 6),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 9, .production_id = 12),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 9, .production_id = 11),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 10),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 10, .production_id = 14),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 5),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 7),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 9),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__name_list, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__name_list, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_list, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_in_list, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sig_in_list_repeat1, 2),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sig_in_list_repeat1, 2), SHIFT_REPEAT(82),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_in_list, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 4),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 3),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__field_list, 3), SHIFT(88),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 1),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__field_list, 1), SHIFT(6),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 4),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 6),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 5),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_in, 2, .production_id = 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_extends, 2, .production_id = 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_list, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicity, 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [260] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_alloy6(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
